use crate::types::CompressionType;

// this is missing from autogenerated code, so we implement it ourselves
impl From<String> for CompressionType {
    fn from(value: String) -> Self {
        serde_json::from_str(&value).expect("couldn't conver enum value")
    }
}
