/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApResponseErrorType {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "validation")]
    Validation,

}

impl std::fmt::Display for ApResponseErrorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Error => write!(f, "error"),
            Self::Validation => write!(f, "validation"),
        }
    }
}

impl Default for ApResponseErrorType {
    fn default() -> ApResponseErrorType {
        Self::Error
    }
}

