/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BucketLifecycleConfiguration : Configuration for automatic object lifecycle in storage buckets.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketLifecycleConfiguration {
    /// Number of days after which objects will expire automatically.
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<i32>,
}

impl BucketLifecycleConfiguration {
    /// Configuration for automatic object lifecycle in storage buckets.
    pub fn new() -> BucketLifecycleConfiguration {
        BucketLifecycleConfiguration {
            days: None,
        }
    }
}

