/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompressRequest {
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<String>>,
    #[serde(rename = "compression", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compression: Option<Option<models::CompressionType>>,
    #[serde(rename = "dereference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dereference: Option<Option<bool>>,
    #[serde(rename = "matchPattern", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub match_pattern: Option<Option<String>>,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
    /// Target path of the compress operation
    #[serde(rename = "targetPath")]
    pub target_path: String,
}

impl CompressRequest {
    pub fn new(source_path: Option<String>, target_path: String) -> CompressRequest {
        CompressRequest {
            account: None,
            compression: None,
            dereference: None,
            match_pattern: None,
            source_path,
            target_path,
        }
    }
}

