/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataOperation {
    #[serde(rename = "data_transfer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_transfer: Option<Option<Box<models::DataOperationDataTransfer>>>,
    /// Maximum file size (in bytes) allowed for direct upload and download. Larger files will go through the staging area.
    #[serde(rename = "max_ops_file_size", skip_serializing_if = "Option::is_none")]
    pub max_ops_file_size: Option<i32>,
}

impl DataOperation {
    pub fn new() -> DataOperation {
        DataOperation {
            data_transfer: None,
            max_ops_file_size: None,
        }
    }
}

