/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "serviceType")]
pub enum DataOperationDataTransfer {
    #[serde(rename="s3")]
    S3(Box<models::S3DataTransfer>),
    #[serde(rename="wormhole")]
    Wormhole(Box<models::WormholeDataTransfer>),
}

impl Default for DataOperationDataTransfer {
    fn default() -> Self {
        Self::S3(Default::default())
    }
}


