/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteResponse {
    #[serde(rename = "transferJob")]
    pub transfer_job: Box<models::TransferJob>,
}

impl DeleteResponse {
    pub fn new(transfer_job: models::TransferJob) -> DeleteResponse {
        DeleteResponse {
            transfer_job: Box::new(transfer_job),
        }
    }
}

