/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadFileResponse {
    #[serde(rename = "transferDirectives", skip_serializing_if = "Option::is_none")]
    pub transfer_directives: Option<Box<models::Transferdirectives>>,
    #[serde(rename = "transferJob")]
    pub transfer_job: Box<models::TransferJob>,
}

impl DownloadFileResponse {
    pub fn new(transfer_job: models::TransferJob) -> DownloadFileResponse {
        DownloadFileResponse {
            transfer_directives: None,
            transfer_job: Box::new(transfer_job),
        }
    }
}

