/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Env : Dictionary of environment variables to set in the job context
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Env {
}

impl Env {
    /// Dictionary of environment variables to set in the job context
    pub fn new() -> Env {
        Env {
        }
    }
}

