/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileSystemDataType : Data types for cluster file systems.
/// Data types for cluster file systems.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileSystemDataType {
    #[serde(rename = "users")]
    Users,
    #[serde(rename = "store")]
    Store,
    #[serde(rename = "archive")]
    Archive,
    #[serde(rename = "apps")]
    Apps,
    #[serde(rename = "scratch")]
    Scratch,
    #[serde(rename = "project")]
    Project,

}

impl std::fmt::Display for FileSystemDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Users => write!(f, "users"),
            Self::Store => write!(f, "store"),
            Self::Archive => write!(f, "archive"),
            Self::Apps => write!(f, "apps"),
            Self::Scratch => write!(f, "scratch"),
            Self::Project => write!(f, "project"),
        }
    }
}

impl Default for FileSystemDataType {
    fn default() -> FileSystemDataType {
        Self::Users
    }
}

