/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileStat {
    #[serde(rename = "atime")]
    pub atime: i32,
    #[serde(rename = "ctime")]
    pub ctime: i32,
    #[serde(rename = "dev")]
    pub dev: i32,
    #[serde(rename = "gid")]
    pub gid: i32,
    #[serde(rename = "ino")]
    pub ino: i32,
    #[serde(rename = "mode")]
    pub mode: i32,
    #[serde(rename = "mtime")]
    pub mtime: i32,
    #[serde(rename = "nlink")]
    pub nlink: i32,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "uid")]
    pub uid: i32,
}

impl FileStat {
    pub fn new(atime: i32, ctime: i32, dev: i32, gid: i32, ino: i32, mode: i32, mtime: i32, nlink: i32, size: i32, uid: i32) -> FileStat {
        FileStat {
            atime,
            ctime,
            dev,
            gid,
            ino,
            mode,
            mtime,
            nlink,
            size,
            uid,
        }
    }
}

