/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "linkTarget", deserialize_with = "Option::deserialize")]
    pub link_target: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: String,
    #[serde(rename = "size")]
    pub size: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl File {
    pub fn new(group: String, last_modified: String, link_target: Option<String>, name: String, permissions: String, size: String, r#type: String, user: String) -> File {
        File {
            group,
            last_modified,
            link_target,
            name,
            permissions,
            size,
            r#type,
            user,
        }
    }
}

