/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileSystem : Defines a cluster file system and its type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileSystem {
    /// File system purpose/type.
    #[serde(rename = "dataType")]
    pub data_type: models::FileSystemDataType,
    /// Mark this as the default working directory.
    #[serde(rename = "defaultWorkDir", skip_serializing_if = "Option::is_none")]
    pub default_work_dir: Option<bool>,
    /// Mount path for the file system.
    #[serde(rename = "path")]
    pub path: String,
}

impl FileSystem {
    /// Defines a cluster file system and its type.
    pub fn new(data_type: models::FileSystemDataType, path: String) -> FileSystem {
        FileSystem {
            data_type,
            default_work_dir: None,
            path,
        }
    }
}

