/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileContent {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "contentType")]
    pub content_type: models::ContentUnit,
    #[serde(rename = "endPosition")]
    pub end_position: i32,
    #[serde(rename = "startPosition")]
    pub start_position: i32,
}

impl FileContent {
    pub fn new(content: String, content_type: models::ContentUnit, end_position: i32, start_position: i32) -> FileContent {
        FileContent {
            content,
            content_type,
            end_position,
            start_position,
        }
    }
}

