/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilesystemServiceHealth : Health check for a mounted file system.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesystemServiceHealth {
    #[serde(rename = "healthy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub healthy: Option<Option<bool>>,
    #[serde(rename = "lastChecked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_checked: Option<Option<String>>,
    #[serde(rename = "latency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latency: Option<Option<f64>>,
    #[serde(rename = "message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message: Option<Option<String>>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    /// Type of the service being checked.
    #[serde(rename = "serviceType")]
    pub service_type: models::HealthCheckType,
}

impl FilesystemServiceHealth {
    /// Health check for a mounted file system.
    pub fn new(service_type: models::HealthCheckType) -> FilesystemServiceHealth {
        FilesystemServiceHealth {
            healthy: None,
            last_checked: None,
            latency: None,
            message: None,
            path: None,
            service_type,
        }
    }
}

