/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLiveness {
    #[serde(rename = "healthcheckRuns", skip_serializing_if = "Option::is_none")]
    pub healthcheck_runs: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<i32>,
}

impl GetLiveness {
    pub fn new() -> GetLiveness {
        GetLiveness {
            healthcheck_runs: None,
            last_update: None,
        }
    }
}

