/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJobResponse {
    #[serde(rename = "jobs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Option<Vec<models::JobModel>>>,
}

impl GetJobResponse {
    pub fn new() -> GetJobResponse {
        GetJobResponse {
            jobs: None,
        }
    }
}

