/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJobMetadataResponse {
    #[serde(rename = "jobs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Option<Vec<models::JobMetadataModel>>>,
}

impl GetJobMetadataResponse {
    pub fn new() -> GetJobMetadataResponse {
        GetJobMetadataResponse {
            jobs: None,
        }
    }
}

