/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFileTailResponse {
    #[serde(rename = "output", deserialize_with = "Option::deserialize")]
    pub output: Option<Box<models::FileContent>>,
}

impl GetFileTailResponse {
    pub fn new(output: Option<models::FileContent>) -> GetFileTailResponse {
        GetFileTailResponse {
            output: if let Some(x) = output {Some(Box::new(x))} else {None},
        }
    }
}

