/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPartitionsResponse {
    #[serde(rename = "partitions")]
    pub partitions: Vec<models::PartitionModel>,
}

impl GetPartitionsResponse {
    pub fn new(partitions: Vec<models::PartitionModel>) -> GetPartitionsResponse {
        GetPartitionsResponse {
            partitions,
        }
    }
}

