/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetReservationsResponse {
    #[serde(rename = "reservations")]
    pub reservations: Vec<models::ReservationModel>,
}

impl GetReservationsResponse {
    pub fn new(reservations: Vec<models::ReservationModel>) -> GetReservationsResponse {
        GetReservationsResponse {
            reservations,
        }
    }
}

