/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetViewFileResponse {
    #[serde(rename = "output", deserialize_with = "Option::deserialize")]
    pub output: Option<String>,
}

impl GetViewFileResponse {
    pub fn new(output: Option<String>) -> GetViewFileResponse {
        GetViewFileResponse {
            output,
        }
    }
}

