/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSystemsResponse {
    #[serde(rename = "dataOperation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_operation: Option<Option<Box<models::DataOperation>>>,
    #[serde(rename = "systems")]
    pub systems: Vec<models::HpcCluster>,
}

impl GetSystemsResponse {
    pub fn new(systems: Vec<models::HpcCluster>) -> GetSystemsResponse {
        GetSystemsResponse {
            data_operation: None,
            systems,
        }
    }
}

