/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HealthCheckType : Types of services that can be health-checked.
/// Types of services that can be health-checked.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthCheckType {
    #[serde(rename = "scheduler")]
    Scheduler,
    #[serde(rename = "filesystem")]
    Filesystem,
    #[serde(rename = "ssh")]
    Ssh,
    #[serde(rename = "s3")]
    S3,
    #[serde(rename = "exception")]
    Exception,

}

impl std::fmt::Display for HealthCheckType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Scheduler => write!(f, "scheduler"),
            Self::Filesystem => write!(f, "filesystem"),
            Self::Ssh => write!(f, "ssh"),
            Self::S3 => write!(f, "s3"),
            Self::Exception => write!(f, "exception"),
        }
    }
}

impl Default for HealthCheckType {
    fn default() -> HealthCheckType {
        Self::Scheduler
    }
}

