/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HpcCluster : Definition of an HPC cluster, including SSH access, scheduling, and filesystem layout. More info in [the systems' section](../arch/systems//README.md).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HpcCluster {
    /// Custom scheduler flags passed to data transfer jobs (e.g. `-pxfer` for a dedicated partition).
    #[serde(rename = "datatransferJobsDirectives", skip_serializing_if = "Option::is_none")]
    pub datatransfer_jobs_directives: Option<Vec<String>>,
    /// List of mounted file systems on the cluster, such as scratch or home directories.
    #[serde(rename = "fileSystems", skip_serializing_if = "Option::is_none")]
    pub file_systems: Option<Vec<models::FileSystem>>,
    /// Unique name for the cluster. This field is case insensitive.
    #[serde(rename = "name")]
    pub name: String,
    /// Probing configuration for monitoring the cluster.
    #[serde(rename = "probing")]
    pub probing: Box<models::Probing>,
    /// Job scheduler configuration.
    #[serde(rename = "scheduler")]
    pub scheduler: Box<models::Scheduler>,
    #[serde(rename = "servicesHealth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub services_health: Option<Option<Vec<models::HpcClusterServicesHealthInner>>>,
    /// SSH configuration for accessing the cluster nodes.
    #[serde(rename = "ssh")]
    pub ssh: Box<models::SshClientPool>,
}

impl HpcCluster {
    /// Definition of an HPC cluster, including SSH access, scheduling, and filesystem layout. More info in [the systems' section](../arch/systems//README.md).
    pub fn new(name: String, probing: models::Probing, scheduler: models::Scheduler, ssh: models::SshClientPool) -> HpcCluster {
        HpcCluster {
            datatransfer_jobs_directives: None,
            file_systems: None,
            name,
            probing: Box::new(probing),
            scheduler: Box::new(scheduler),
            services_health: None,
            ssh: Box::new(ssh),
        }
    }
}

