/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDescriptionModel {
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<String>>,
    #[serde(rename = "constraints", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub constraints: Option<Option<String>>,
    #[serde(rename = "env", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub env: Option<Option<Box<models::Env>>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Script for the job
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    /// Path to the job in target system
    #[serde(rename = "scriptPath", skip_serializing_if = "Option::is_none")]
    pub script_path: Option<String>,
    #[serde(rename = "standardError", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_error: Option<Option<String>>,
    #[serde(rename = "standardInput", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_input: Option<Option<String>>,
    #[serde(rename = "standardOutput", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_output: Option<Option<String>>,
    /// Job working directory
    #[serde(rename = "working_directory")]
    pub working_directory: String,
}

impl JobDescriptionModel {
    pub fn new(working_directory: String) -> JobDescriptionModel {
        JobDescriptionModel {
            account: None,
            constraints: None,
            env: None,
            name: None,
            script: None,
            script_path: None,
            standard_error: None,
            standard_input: None,
            standard_output: None,
            working_directory,
        }
    }
}

