/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobMetadataModel {
    #[serde(rename = "jobId")]
    pub job_id: i32,
    #[serde(rename = "script", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub script: Option<Option<String>>,
    #[serde(rename = "standardError", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_error: Option<Option<String>>,
    #[serde(rename = "standardInput", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_input: Option<Option<String>>,
    #[serde(rename = "standardOutput", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_output: Option<Option<String>>,
}

impl JobMetadataModel {
    pub fn new(job_id: i32) -> JobMetadataModel {
        JobMetadataModel {
            job_id,
            script: None,
            standard_error: None,
            standard_input: None,
            standard_output: None,
        }
    }
}

