/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobTask {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: Box<models::JobStatus>,
    #[serde(rename = "time")]
    pub time: Box<models::JobTime>,
}

impl JobTask {
    pub fn new(id: String, name: String, status: models::JobStatus, time: models::JobTime) -> JobTask {
        JobTask {
            id,
            name,
            status: Box::new(status),
            time: Box::new(time),
        }
    }
}

