/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobStatus {
    #[serde(rename = "exitCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<Option<i32>>,
    #[serde(rename = "interruptSignal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interrupt_signal: Option<Option<i32>>,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "stateReason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state_reason: Option<Option<String>>,
}

impl JobStatus {
    pub fn new(state: String) -> JobStatus {
        JobStatus {
            exit_code: None,
            interrupt_signal: None,
            state,
            state_reason: None,
        }
    }
}

