/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobModel {
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<String>>,
    #[serde(rename = "allocationNodes")]
    pub allocation_nodes: i32,
    #[serde(rename = "cluster")]
    pub cluster: String,
    #[serde(rename = "group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group: Option<Option<String>>,
    #[serde(rename = "jobId")]
    pub job_id: i32,
    #[serde(rename = "killRequestUser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kill_request_user: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nodes")]
    pub nodes: String,
    #[serde(rename = "partition")]
    pub partition: String,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    #[serde(rename = "status")]
    pub status: Box<models::JobStatus>,
    #[serde(rename = "tasks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Option<Vec<models::JobTask>>>,
    #[serde(rename = "time")]
    pub time: Box<models::JobTime>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<String>,
    #[serde(rename = "workingDirectory")]
    pub working_directory: String,
}

impl JobModel {
    pub fn new(allocation_nodes: i32, cluster: String, job_id: i32, name: String, nodes: String, partition: String, status: models::JobStatus, time: models::JobTime, user: Option<String>, working_directory: String) -> JobModel {
        JobModel {
            account: None,
            allocation_nodes,
            cluster,
            group: None,
            job_id,
            kill_request_user: None,
            name,
            nodes,
            partition,
            priority: None,
            status: Box::new(status),
            tasks: None,
            time: Box::new(time),
            user,
            working_directory,
        }
    }
}

