/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobTime {
    #[serde(rename = "elapsed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub elapsed: Option<Option<i32>>,
    #[serde(rename = "end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end: Option<Option<i32>>,
    #[serde(rename = "limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Option<i32>>,
    #[serde(rename = "start", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start: Option<Option<i32>>,
    #[serde(rename = "suspended", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub suspended: Option<Option<i32>>,
}

impl JobTime {
    pub fn new() -> JobTime {
        JobTime {
            elapsed: None,
            end: None,
            limit: None,
            start: None,
            suspended: None,
        }
    }
}

