/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultipartUpload : Configuration for multipart upload behavior.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultipartUpload {
    /// Maximum size (in bytes) for multipart data transfers. Default is 2 GB.
    #[serde(rename = "max_part_size", skip_serializing_if = "Option::is_none")]
    pub max_part_size: Option<i32>,
    /// Number of parts to upload in parallel to the staging area.
    #[serde(rename = "parallel_runs", skip_serializing_if = "Option::is_none")]
    pub parallel_runs: Option<i32>,
    /// Temporary folder used for storing split parts during upload.
    #[serde(rename = "tmp_folder", skip_serializing_if = "Option::is_none")]
    pub tmp_folder: Option<String>,
    /// Enable or disable splitting large files into parts when uploading the file to the staging area.
    #[serde(rename = "use_split", skip_serializing_if = "Option::is_none")]
    pub use_split: Option<bool>,
}

impl MultipartUpload {
    /// Configuration for multipart upload behavior.
    pub fn new() -> MultipartUpload {
        MultipartUpload {
            max_part_size: None,
            parallel_runs: None,
            tmp_folder: None,
            use_split: None,
        }
    }
}

