/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeModel {
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<String>>,
    #[serde(rename = "allocCpus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alloc_cpus: Option<Option<i32>>,
    #[serde(rename = "allocMemory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alloc_memory: Option<Option<i32>>,
    #[serde(rename = "cores", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cores: Option<Option<i32>>,
    #[serde(rename = "cpuLoad", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu_load: Option<Option<f64>>,
    #[serde(rename = "cpus")]
    pub cpus: i32,
    #[serde(rename = "features", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub features: Option<Option<Box<models::Features>>>,
    #[serde(rename = "freeMemory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub free_memory: Option<Option<i32>>,
    #[serde(rename = "hostname", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<Option<String>>,
    #[serde(rename = "idleCpus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub idle_cpus: Option<Option<i32>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partitions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub partitions: Option<Option<Vec<String>>>,
    #[serde(rename = "sockets", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sockets: Option<Option<i32>>,
    #[serde(rename = "state")]
    pub state: Box<models::State>,
    #[serde(rename = "threads", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub threads: Option<Option<i32>>,
    #[serde(rename = "weight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight: Option<Option<i32>>,
}

impl NodeModel {
    pub fn new(cpus: i32, name: String, state: models::State) -> NodeModel {
        NodeModel {
            address: None,
            alloc_cpus: None,
            alloc_memory: None,
            cores: None,
            cpu_load: None,
            cpus,
            features: None,
            free_memory: None,
            hostname: None,
            idle_cpus: None,
            name,
            partitions: None,
            sockets: None,
            state: Box::new(state),
            threads: None,
            weight: None,
        }
    }
}

