/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionModel {
    #[serde(rename = "cpus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<Option<i32>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partition")]
    pub partition: Box<models::Partition>,
    #[serde(rename = "totalNodes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_nodes: Option<Option<i32>>,
}

impl PartitionModel {
    pub fn new(name: String, partition: models::Partition) -> PartitionModel {
        PartitionModel {
            cpus: None,
            name,
            partition: Box::new(partition),
            total_nodes: None,
        }
    }
}

