/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostMakeDirRequest {
    #[serde(rename = "parent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Option<bool>>,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
}

impl PostMakeDirRequest {
    pub fn new(source_path: Option<String>) -> PostMakeDirRequest {
        PostMakeDirRequest {
            parent: None,
            source_path,
        }
    }
}

