/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostFileUploadRequest {
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<String>>,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
    #[serde(rename = "transferDirectives")]
    pub transfer_directives: Box<models::Transferdirectives1>,
}

impl PostFileUploadRequest {
    pub fn new(source_path: Option<String>, transfer_directives: models::Transferdirectives1) -> PostFileUploadRequest {
        PostFileUploadRequest {
            account: None,
            source_path,
            transfer_directives: Box::new(transfer_directives),
        }
    }
}

