/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostJobSubmissionResponse {
    #[serde(rename = "jobId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<Option<i32>>,
}

impl PostJobSubmissionResponse {
    pub fn new() -> PostJobSubmissionResponse {
        PostJobSubmissionResponse {
            job_id: None,
        }
    }
}

