/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostFileSymlinkRequest {
    /// Path to the new symlink
    #[serde(rename = "linkPath")]
    pub link_path: String,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
}

impl PostFileSymlinkRequest {
    pub fn new(link_path: String, source_path: Option<String>) -> PostFileSymlinkRequest {
        PostFileSymlinkRequest {
            link_path,
            source_path,
        }
    }
}

