/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostJobAttachRequest {
    /// Command to attach to the job
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl PostJobAttachRequest {
    pub fn new() -> PostJobAttachRequest {
        PostJobAttachRequest {
            command: None,
        }
    }
}

