/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostExtractRequest {
    #[serde(rename = "compression", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compression: Option<Option<models::CompressionType>>,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
    /// Path to the directory where to extract the compressed file
    #[serde(rename = "targetPath")]
    pub target_path: String,
}

impl PostExtractRequest {
    pub fn new(source_path: Option<String>, target_path: String) -> PostExtractRequest {
        PostExtractRequest {
            compression: None,
            source_path,
            target_path,
        }
    }
}

