/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Probing : Cluster monitoring attributes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Probing {
    /// Interval in seconds between cluster checks.
    #[serde(rename = "interval")]
    pub interval: i32,
    /// Maximum time in seconds allowed per check.
    #[serde(rename = "timeout")]
    pub timeout: i32,
}

impl Probing {
    /// Cluster monitoring attributes.
    pub fn new(interval: i32, timeout: i32) -> Probing {
        Probing {
            interval,
            timeout,
        }
    }
}

