/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutFileChmodRequest {
    /// Mode in octal permission format
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
}

impl PutFileChmodRequest {
    pub fn new(mode: String, source_path: Option<String>) -> PutFileChmodRequest {
        PutFileChmodRequest {
            mode,
            source_path,
        }
    }
}

