/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutFileChownRequest {
    #[serde(rename = "group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group: Option<Option<String>>,
    #[serde(rename = "owner", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Option<String>>,
    #[serde(rename = "sourcePath", deserialize_with = "Option::deserialize")]
    pub source_path: Option<String>,
}

impl PutFileChownRequest {
    pub fn new(source_path: Option<String>) -> PutFileChownRequest {
        PutFileChownRequest {
            group: None,
            owner: None,
            source_path,
        }
    }
}

