/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReservationModel {
    #[serde(rename = "endTime")]
    pub end_time: i32,
    #[serde(rename = "features", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub features: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nodeList")]
    pub node_list: String,
    #[serde(rename = "startTime")]
    pub start_time: i32,
}

impl ReservationModel {
    pub fn new(end_time: i32, name: String, node_list: String, start_time: i32) -> ReservationModel {
        ReservationModel {
            end_time,
            features: None,
            name,
            node_list,
            start_time,
        }
    }
}

