/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// S3DataTransfer : Object storage configuration, including credentials, endpoints, and upload behavior.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3DataTransfer {
    /// Access key ID for S3-compatible storage.
    #[serde(rename = "accessKeyId")]
    pub access_key_id: String,
    /// Lifecycle policy settings for auto-deleting files after a given number of days.
    #[serde(rename = "bucketLifecycleConfiguration", skip_serializing_if = "Option::is_none")]
    pub bucket_lifecycle_configuration: Option<Box<models::BucketLifecycleConfiguration>>,
    /// Settings for multipart upload, including chunk size and concurrency.
    #[serde(rename = "multipart", skip_serializing_if = "Option::is_none")]
    pub multipart: Option<Box<models::MultipartUpload>>,
    /// Name identifier for the storage.
    #[serde(rename = "name")]
    pub name: String,
    /// Private/internal endpoint URL for the storage.
    #[serde(rename = "privateUrl")]
    pub private_url: String,
    #[serde(rename = "probing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub probing: Option<Option<Box<models::Probing>>>,
    /// Public/external URL for the storage.
    #[serde(rename = "publicUrl")]
    pub public_url: String,
    /// Region of the storage bucket.
    #[serde(rename = "region")]
    pub region: String,
    /// Secret access key for storage. You can give directly the content or the file path using `'secret_file:/path/to/file'`.
    #[serde(rename = "secretAccessKey")]
    pub secret_access_key: String,
    #[serde(rename = "serviceType")]
    pub service_type: ServiceType,
    #[serde(rename = "servicesHealth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub services_health: Option<Option<Vec<models::S3DataTransferServicesHealthInner>>>,
    #[serde(rename = "tenant", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Option<String>>,
    /// Time-to-live (in seconds) for generated URLs.
    #[serde(rename = "ttl")]
    pub ttl: i32,
}

impl S3DataTransfer {
    /// Object storage configuration, including credentials, endpoints, and upload behavior.
    pub fn new(access_key_id: String, name: String, private_url: String, public_url: String, region: String, secret_access_key: String, service_type: ServiceType, ttl: i32) -> S3DataTransfer {
        S3DataTransfer {
            access_key_id,
            bucket_lifecycle_configuration: None,
            multipart: None,
            name,
            private_url,
            probing: None,
            public_url,
            region,
            secret_access_key,
            service_type,
            services_health: None,
            tenant: None,
            ttl,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceType {
    #[serde(rename = "s3")]
    S3,
}

impl Default for ServiceType {
    fn default() -> ServiceType {
        Self::S3
    }
}

