/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3DataTransferDirective {
    #[serde(rename = "completeUploadUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub complete_upload_url: Option<Option<String>>,
    #[serde(rename = "downloadUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<Option<String>>,
    #[serde(rename = "fileSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<Option<i32>>,
    #[serde(rename = "maxPartSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_part_size: Option<Option<i32>>,
    #[serde(rename = "partsUploadUrls", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parts_upload_urls: Option<Option<Vec<String>>>,
    #[serde(rename = "transferMethod")]
    pub transfer_method: TransferMethod,
}

impl S3DataTransferDirective {
    pub fn new(transfer_method: TransferMethod) -> S3DataTransferDirective {
        S3DataTransferDirective {
            complete_upload_url: None,
            download_url: None,
            file_size: None,
            max_part_size: None,
            parts_upload_urls: None,
            transfer_method,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferMethod {
    #[serde(rename = "s3")]
    S3,
}

impl Default for TransferMethod {
    fn default() -> TransferMethod {
        Self::S3
    }
}

