/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3DataTransferServicesHealthInner {
    #[serde(rename = "healthy", skip_serializing_if = "Option::is_none")]
    pub healthy: Option<bool>,
    #[serde(rename = "lastChecked", skip_serializing_if = "Option::is_none")]
    pub last_checked: Option<String>,
    #[serde(rename = "latency", skip_serializing_if = "Option::is_none")]
    pub latency: Option<f64>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Type of the service being checked.
    #[serde(rename = "serviceType")]
    pub service_type: models::HealthCheckType,
}

impl S3DataTransferServicesHealthInner {
    pub fn new(service_type: models::HealthCheckType) -> S3DataTransferServicesHealthInner {
        S3DataTransferServicesHealthInner {
            healthy: None,
            last_checked: None,
            latency: None,
            message: None,
            service_type,
        }
    }
}

