/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Scheduler : Cluster job scheduler configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scheduler {
    #[serde(rename = "apiUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<Option<String>>,
    #[serde(rename = "apiVersion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<Option<String>>,
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i32>>,
    /// Scheduler type.
    #[serde(rename = "type")]
    pub r#type: models::SchedulerType,
    /// Scheduler version.
    #[serde(rename = "version")]
    pub version: String,
}

impl Scheduler {
    /// Cluster job scheduler configuration.
    pub fn new(r#type: models::SchedulerType, version: String) -> Scheduler {
        Scheduler {
            api_url: None,
            api_version: None,
            timeout: None,
            r#type,
            version,
        }
    }
}

