/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshTimeouts : Various SSH settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshTimeouts {
    /// Timeout (seconds) for executing commands over SSH.
    #[serde(rename = "commandExecution", skip_serializing_if = "Option::is_none")]
    pub command_execution: Option<i32>,
    /// Timeout (seconds) for initial SSH connection.
    #[serde(rename = "connection", skip_serializing_if = "Option::is_none")]
    pub connection: Option<i32>,
    /// Max idle time (seconds) before disconnecting.
    #[serde(rename = "idleTimeout", skip_serializing_if = "Option::is_none")]
    pub idle_timeout: Option<i32>,
    /// Interval (seconds) for sending keep-alive messages.
    #[serde(rename = "keepAlive", skip_serializing_if = "Option::is_none")]
    pub keep_alive: Option<i32>,
    /// Timeout (seconds) for SSH login/auth.
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<i32>,
}

impl SshTimeouts {
    /// Various SSH settings.
    pub fn new() -> SshTimeouts {
        SshTimeouts {
            command_execution: None,
            connection: None,
            idle_timeout: None,
            keep_alive: None,
            login: None,
        }
    }
}

