/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SshClientPool : SSH connection pool configuration for remote execution.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SshClientPool {
    /// SSH target hostname.
    #[serde(rename = "host")]
    pub host: String,
    /// Maximum number of concurrent SSH clients.
    #[serde(rename = "maxClients", skip_serializing_if = "Option::is_none")]
    pub max_clients: Option<i32>,
    /// SSH port.
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "proxyHost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proxy_host: Option<Option<String>>,
    #[serde(rename = "proxyPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proxy_port: Option<Option<i32>>,
    /// SSH timeout settings.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Box<models::SshTimeouts>>,
}

impl SshClientPool {
    /// SSH connection pool configuration for remote execution.
    pub fn new(host: String, port: i32) -> SshClientPool {
        SshClientPool {
            host,
            max_clients: None,
            port,
            proxy_host: None,
            proxy_port: None,
            timeout: None,
        }
    }
}

