/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferJobLogs {
    #[serde(rename = "errorLog")]
    pub error_log: String,
    #[serde(rename = "outputLog")]
    pub output_log: String,
}

impl TransferJobLogs {
    pub fn new(error_log: String, output_log: String) -> TransferJobLogs {
        TransferJobLogs {
            error_log,
            output_log,
        }
    }
}

