/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transferdirectives : Provide method specific transfer directives
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "transferMethod")]
pub enum Transferdirectives {
    #[serde(rename="s3")]
    S3(Box<models::S3DataTransferDirective>),
    #[serde(rename="wormhole")]
    Wormhole(Box<models::WormholeDataTransferDirective>),
}

impl Default for Transferdirectives {
    fn default() -> Self {
        Self::S3(Default::default())
    }
}


