/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferJob {
    #[serde(rename = "jobId")]
    pub job_id: i32,
    #[serde(rename = "logs")]
    pub logs: Box<models::TransferJobLogs>,
    #[serde(rename = "system")]
    pub system: String,
    #[serde(rename = "workingDirectory")]
    pub working_directory: String,
}

impl TransferJob {
    pub fn new(job_id: i32, logs: models::TransferJobLogs, system: String, working_directory: String) -> TransferJob {
        TransferJob {
            job_id,
            logs: Box::new(logs),
            system,
            working_directory,
        }
    }
}

