/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transferdirectives1 : Data transfer parameters specific to the transfer method
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transferdirectives1 {
    #[serde(rename = "transferMethod")]
    pub transfer_method: TransferMethod,
    #[serde(rename = "wormholeCode", skip_serializing_if = "Option::is_none")]
    pub wormhole_code: Option<String>,
    #[serde(rename = "completeUploadUrl", skip_serializing_if = "Option::is_none")]
    pub complete_upload_url: Option<String>,
    #[serde(rename = "downloadUrl", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
    #[serde(rename = "fileSize", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i32>,
    #[serde(rename = "maxPartSize", skip_serializing_if = "Option::is_none")]
    pub max_part_size: Option<i32>,
    #[serde(rename = "partsUploadUrls", skip_serializing_if = "Option::is_none")]
    pub parts_upload_urls: Option<Vec<String>>,
}

impl Transferdirectives1 {
    /// Data transfer parameters specific to the transfer method
    pub fn new(transfer_method: TransferMethod) -> Transferdirectives1 {
        Transferdirectives1 {
            transfer_method,
            wormhole_code: None,
            complete_upload_url: None,
            download_url: None,
            file_size: None,
            max_part_size: None,
            parts_upload_urls: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferMethod {
    #[serde(rename = "s3")]
    S3,
}

impl Default for TransferMethod {
    fn default() -> TransferMethod {
        Self::S3
    }
}

