/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInfoResponse {
    #[serde(rename = "group")]
    pub group: Box<models::PosixIdentified>,
    #[serde(rename = "groups")]
    pub groups: Vec<models::PosixIdentified>,
    #[serde(rename = "user")]
    pub user: Box<models::PosixIdentified>,
}

impl UserInfoResponse {
    pub fn new(group: models::PosixIdentified, groups: Vec<models::PosixIdentified>, user: models::PosixIdentified) -> UserInfoResponse {
        UserInfoResponse {
            group: Box::new(group),
            groups,
            user: Box::new(user),
        }
    }
}

