/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WormholeDataTransfer {
    #[serde(rename = "probing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub probing: Option<Option<Box<models::Probing>>>,
    #[serde(rename = "serviceType")]
    pub service_type: ServiceType,
    #[serde(rename = "servicesHealth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub services_health: Option<Option<Vec<models::S3DataTransferServicesHealthInner>>>,
}

impl WormholeDataTransfer {
    pub fn new(service_type: ServiceType) -> WormholeDataTransfer {
        WormholeDataTransfer {
            probing: None,
            service_type,
            services_health: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceType {
    #[serde(rename = "wormhole")]
    Wormhole,
}

impl Default for ServiceType {
    fn default() -> ServiceType {
        Self::Wormhole
    }
}

