/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WormholeDataTransferDirective {
    #[serde(rename = "transferMethod")]
    pub transfer_method: TransferMethod,
    #[serde(rename = "wormholeCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wormhole_code: Option<Option<String>>,
}

impl WormholeDataTransferDirective {
    pub fn new(transfer_method: TransferMethod) -> WormholeDataTransferDirective {
        WormholeDataTransferDirective {
            transfer_method,
            wormhole_code: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferMethod {
    #[serde(rename = "wormhole")]
    Wormhole,
}

impl Default for TransferMethod {
    fn default() -> TransferMethod {
        Self::Wormhole
    }
}

