/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`attach_compute_system_name_jobs_job_id_attach_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttachComputeSystemNameJobsJobIdAttachPutError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_job_cancel_compute_system_name_jobs_job_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteJobCancelComputeSystemNameJobsJobIdDeleteError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_job_compute_system_name_jobs_job_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetJobComputeSystemNameJobsJobIdGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_job_metadata_compute_system_name_jobs_job_id_metadata_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetJobMetadataComputeSystemNameJobsJobIdMetadataGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_jobs_compute_system_name_jobs_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetJobsComputeSystemNameJobsGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_job_submit_compute_system_name_jobs_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostJobSubmitComputeSystemNameJobsPostError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}


/// Attach a procces to a job by `{job_id}`
pub async fn attach_compute_system_name_jobs_job_id_attach_put(configuration: &configuration::Configuration, job_id: &str, system_name: &str, post_job_attach_request: models::PostJobAttachRequest) -> Result<(), Error<AttachComputeSystemNameJobsJobIdAttachPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_job_id = job_id;
    let p_path_system_name = system_name;
    let p_body_post_job_attach_request = post_job_attach_request;

    let uri_str = format!("{}/compute/{system_name}/jobs/{job_id}/attach", configuration.base_path, job_id=crate::apis::urlencode(p_path_job_id), system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_post_job_attach_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttachComputeSystemNameJobsJobIdAttachPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Cancel a job
pub async fn delete_job_cancel_compute_system_name_jobs_job_id_delete(configuration: &configuration::Configuration, job_id: &str, system_name: &str) -> Result<(), Error<DeleteJobCancelComputeSystemNameJobsJobIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_job_id = job_id;
    let p_path_system_name = system_name;

    let uri_str = format!("{}/compute/{system_name}/jobs/{job_id}", configuration.base_path, job_id=crate::apis::urlencode(p_path_job_id), system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteJobCancelComputeSystemNameJobsJobIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get status of a job by `{job_id}`
pub async fn get_job_compute_system_name_jobs_job_id_get(configuration: &configuration::Configuration, job_id: &str, system_name: &str) -> Result<models::GetJobResponse, Error<GetJobComputeSystemNameJobsJobIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_job_id = job_id;
    let p_path_system_name = system_name;

    let uri_str = format!("{}/compute/{system_name}/jobs/{job_id}", configuration.base_path, job_id=crate::apis::urlencode(p_path_job_id), system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetJobResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetJobResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetJobComputeSystemNameJobsJobIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get metadata of a job by `{job_id}`
pub async fn get_job_metadata_compute_system_name_jobs_job_id_metadata_get(configuration: &configuration::Configuration, job_id: &str, system_name: &str) -> Result<models::GetJobMetadataResponse, Error<GetJobMetadataComputeSystemNameJobsJobIdMetadataGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_job_id = job_id;
    let p_path_system_name = system_name;

    let uri_str = format!("{}/compute/{system_name}/jobs/{job_id}/metadata", configuration.base_path, job_id=crate::apis::urlencode(p_path_job_id), system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetJobMetadataResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetJobMetadataResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetJobMetadataComputeSystemNameJobsJobIdMetadataGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get status of all jobs
pub async fn get_jobs_compute_system_name_jobs_get(configuration: &configuration::Configuration, system_name: &str, allusers: Option<bool>) -> Result<models::GetJobResponse, Error<GetJobsComputeSystemNameJobsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;
    let p_query_allusers = allusers;

    let uri_str = format!("{}/compute/{system_name}/jobs", configuration.base_path, system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_allusers {
        req_builder = req_builder.query(&[("allusers", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetJobResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetJobResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetJobsComputeSystemNameJobsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Submit a new job
pub async fn post_job_submit_compute_system_name_jobs_post(configuration: &configuration::Configuration, system_name: &str, post_job_submit_request: models::PostJobSubmitRequest) -> Result<models::PostJobSubmissionResponse, Error<PostJobSubmitComputeSystemNameJobsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;
    let p_body_post_job_submit_request = post_job_submit_request;

    let uri_str = format!("{}/compute/{system_name}/jobs", configuration.base_path, system_name=crate::apis::urlencode(p_path_system_name));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_post_job_submit_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostJobSubmissionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostJobSubmissionResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostJobSubmitComputeSystemNameJobsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

