/*
 * FirecREST
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use std::fs;

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_liveness_status_liveness_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLivenessStatusLivenessGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_system_nodes_status_system_name_nodes_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSystemNodesStatusSystemNameNodesGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_system_partitions_status_system_name_partitions_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSystemPartitionsStatusSystemNamePartitionsGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_system_reservations_status_system_name_reservations_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSystemReservationsStatusSystemNameReservationsGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_systems_status_systems_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSystemsStatusSystemsGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_userinfo_status_system_name_userinfo_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserinfoStatusSystemNameUserinfoGetError {
    Status4XX(models::ApiResponseError),
    Status5XX(models::ApiResponseError),
    UnknownValue(serde_json::Value),
}

/// Get liveness status of FirecREST
pub async fn get_liveness_status_liveness_get(
    configuration: &configuration::Configuration,
) -> Result<models::GetLiveness, Error<GetLivenessStatusLivenessGetError>> {
    let uri_str = format!("{}/status/liveness/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetLiveness`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetLiveness`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetLivenessStatusLivenessGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get the list of nodes of a `{system_name}`
pub async fn get_system_nodes_status_system_name_nodes_get(
    configuration: &configuration::Configuration,
    system_name: &str,
) -> Result<models::GetNodesResponse, Error<GetSystemNodesStatusSystemNameNodesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;

    let uri_str = format!(
        "{}/status/{system_name}/nodes",
        configuration.base_path,
        system_name = crate::apis::urlencode(p_path_system_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetNodesResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetNodesResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSystemNodesStatusSystemNameNodesGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get the list of partitions of a `{system_name}`
pub async fn get_system_partitions_status_system_name_partitions_get(
    configuration: &configuration::Configuration,
    system_name: &str,
) -> Result<
    models::GetPartitionsResponse,
    Error<GetSystemPartitionsStatusSystemNamePartitionsGetError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;

    let uri_str = format!(
        "{}/status/{system_name}/partitions",
        configuration.base_path,
        system_name = crate::apis::urlencode(p_path_system_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetPartitionsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetPartitionsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSystemPartitionsStatusSystemNamePartitionsGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get the list of reservations of a `{system_name}`
pub async fn get_system_reservations_status_system_name_reservations_get(
    configuration: &configuration::Configuration,
    system_name: &str,
) -> Result<
    models::GetReservationsResponse,
    Error<GetSystemReservationsStatusSystemNameReservationsGetError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;

    let uri_str = format!(
        "{}/status/{system_name}/reservations",
        configuration.base_path,
        system_name = crate::apis::urlencode(p_path_system_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetReservationsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetReservationsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSystemReservationsStatusSystemNameReservationsGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get the list of systems and health status
pub async fn get_systems_status_systems_get(
    configuration: &configuration::Configuration,
) -> Result<models::GetSystemsResponse, Error<GetSystemsStatusSystemsGetError>> {
    let uri_str = format!("{}/status/systems", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        fs::write("/tmp/request.json", content.clone())?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetSystemsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetSystemsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSystemsStatusSystemsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get current user information on a `{system_name}`
pub async fn get_userinfo_status_system_name_userinfo_get(
    configuration: &configuration::Configuration,
    system_name: &str,
) -> Result<models::UserInfoResponse, Error<GetUserinfoStatusSystemNameUserinfoGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_system_name = system_name;

    let uri_str = format!(
        "{}/status/{system_name}/userinfo",
        configuration.base_path,
        system_name = crate::apis::urlencode(p_path_system_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserInfoResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UserInfoResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetUserinfoStatusSystemNameUserinfoGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
